# ========== stardew.site ==========
server {
    listen 80;
    server_name stardew.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name stardew.site;

    ssl_certificate     /etc/nginx/stardew.site_bundle.crt;
    ssl_certificate_key /etc/nginx/stardew.site.key;

    # Gzip（可保留）
    gzip on;
    gzip_static on;
    gzip_types text/plain application/x-javascript text/css application/xml
               text/javascript application/x-httpd-php image/jpeg image/gif image/png;

    location / {
        proxy_pass http://127.0.0.1:3888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}